services:
  app:
    build:
      context: .
    container_name: flask-api
    command: flask run --debug --host 0.0.0.0 --port 5000
    env_file:
      - .env
    volumes:
      - "./src:/home/${USER}/src"
    network_mode: host

  db:
    image: postgres:alpine
    restart: on-failure
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    ports:
      - $DB_PORT

