[tool.poetry]
name = "flask-api"
version = "0.1.0"
description = ""
authors = ["Esteban Rodriguez <https://github.com/esteban-alo>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.0"


[tool.poetry.group.dev.dependencies]
autoflake = "^2.2.1"
black = "^23.10.1"
coverage = "^7.3.2"
isort = "^5.12.0"
mypy = "^1.6.1"
pylint = "^3.0.2"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
