[tool.poetry]
name = "flask-api"
version = "0.1.0"
description = ""
authors = ["Esteban Rodriguez <https://github.com/esteban-alo>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
alembic = "^1.13.1"
flask = "^3.0.2"
python-dotenv = "^1.0.1"
sqlalchemy = "^2.0.27"

[tool.poetry.group.dev.dependencies]
autoflake = "^2.3.0"
black = "^24.2.0"
coverage = "^7.4.3"
isort = "^5.13.2"
mypy = "^1.8.0"
pyflakes = "^3.2.0"
pylint = "^3.1.0"
pytest = "^8.0.2"
ruff = "^0.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
